name: "Check competitive-verifier result"
description: "A composite action that check result of competitive-verifier"
author: "Kzrnm"
branding:
  color: blue
  icon: check-circle
inputs:
  local-result-path:
    description: "The file path of ressult json."
    required: false
    default: ""

  result-artifact-prefix:
    description: The name of artifact which contains verify result json.
    required: false
    default: ${{ runner.os }}-competitive-verifier-result
  result-file-name:
    description: "Result json file name."
    required: false
    default: "competitive-verifier-result.json"
outputs:
  result-count:
    description: "Result count"
    value: ${{ steps.check.outputs.size }}
  result-count-success:
    description: "Result count of success"
    value: ${{ steps.check.outputs.success }}
  result-count-failure:
    description: "Result count of failure"
    value: ${{ steps.check.outputs.failure }}
  result-count-skipped:
    description: "Result count of skipped"
    value: ${{ steps.check.outputs.skipped }}
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      if: inputs.local-result-path == ''
      with:
        path: ${{ runner.temp }}/artifacts

    - name: Check verifications
      shell: bash
      id: check
      run: |
        result_group_by=$(jq -sr 'map(.files[].verifications[].status) | group_by(.) | map({key:.[0], value: length})|from_entries' ${RESULT_FILES:=$ARTIFACT_FILES})
        echo "$result_group_by"

        success=$(echo "$result_group_by" |jq '.success//0')
        failure=$(echo "$result_group_by" |jq '.failure//0')
        skipped=$(echo "$result_group_by" |jq '.skipped//0')
        size=$(( $success + $failure + $skipped ))

        echo "success=$success" >> $GITHUB_OUTPUT
        echo "failure=$failure" >> $GITHUB_OUTPUT
        echo "skipped=$skipped" >> $GITHUB_OUTPUT
        echo "size=$size" >> $GITHUB_OUTPUT

        [ $(( $failure > 0 )) = 0 ]
      env:
        RESULT_FILES: ${{ inputs.local-result-path }}
        ARTIFACT_FILES: ${{ runner.temp }}/artifacts/${{ inputs.result-artifact-prefix }}*/${{ inputs.result-file-name }}
